# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8873c7c2bcdcbdcc83b4dabc5081a1596ba21363f24b69ae5b1e8a1efc182395aad0c988d1a9cf914ec6ba0a424f04f6e9d416470e0683d536564c690fcf441

test:
  secret_key_base: 5453bf75103518de78d1ae595bd42c6e591082368dff217d896822c8f090c004d11f229a5c625d0b3918137ad8c85e744a97d017cffc6f064c11f3c043a2039e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
